version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: fastapi-backend
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery-worker
    command: celery -A core.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
